### ISSUE TITLE
code continuity:  sample code should use SDKs

### ISSUE THREAD

**Issue by dougsillars** [mindee/devrel#71] opened 2021-09-24 01:23 UTC
Would it be possiible to use SDK code for Pythoin and NodeJS in the Documentation sections on platform.mindee.com?

For example:
https://platform.mindee.com/apishub/products/mindee/expense_receipts?setup=default#documentation
![image](https://user-images.githubusercontent.com/1514288/134604097-03a86da6-cdd2-411c-9f56-4ff42931afd7.png)

There's nothing materially incorrect here - but the SDK is easier to use, so we should promote it everywhere we can.

**Comment by fharper** [comment] 2021-10-12 20:50
I think we should have both, putting the SDK one before, WDYT?

@jonathanMindee ^

**Comment by fharper** [comment] 2022-01-28 16:47
Duplicate of the issues in the documentation repo

**Closed by fharper** 2022-01-28 16:47 UTC
Labels: duplicate
